"""customer management

Creates the customer directory: customers, contact_details, interactions,
notes, and attachments. Every child table cascades from ``customers.id``.

NOTE: ``downgrade()`` drops the tables and the three named enum types, but it
does NOT remove attachment files from disk. Clean those up manually under
``CRM_ATTACHMENTS_DIR`` (default ``backend/var/attachments``) after a rollback.

Revision ID: 0001
Revises:
Create Date: 2026-08-25

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='customer_status'), server_default='active', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_display_name'), 'customers', ['display_name'], unique=False)
    op.create_table('contact_details',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('phone', 'email', 'address', 'other', name='contact_kind'), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_details_customer_id'), 'contact_details', ['customer_id'], unique=False)
    op.create_index('uq_contact_primary_per_kind', 'contact_details', ['customer_id', 'kind'], unique=True, postgresql_where=sa.text('is_primary'), sqlite_where=sa.text('is_primary'))
    op.create_table('interactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('call', 'email', 'meeting', 'chat', 'other', name='interaction_kind'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_customer_id'), 'interactions', ['customer_id'], unique=False)
    op.create_index('ix_interactions_customer_occurred', 'interactions', ['customer_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index(op.f('ix_interactions_occurred_at'), 'interactions', ['occurred_at'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_customer_id'), 'notes', ['customer_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('note_id', sa.Uuid(), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_customer_id'), 'attachments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_attachments_note_id'), 'attachments', ['note_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_note_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_customer_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_notes_customer_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_interactions_occurred_at'), table_name='interactions')
    op.drop_index('ix_interactions_customer_occurred', table_name='interactions')
    op.drop_index(op.f('ix_interactions_customer_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index('uq_contact_primary_per_kind', table_name='contact_details', postgresql_where=sa.text('is_primary'), sqlite_where=sa.text('is_primary'))
    op.drop_index(op.f('ix_contact_details_customer_id'), table_name='contact_details')
    op.drop_table('contact_details')
    op.drop_index(op.f('ix_customers_display_name'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###

    # Postgres keeps named enum types after their tables are dropped; remove
    # them so `upgrade` can run again cleanly. No-op on SQLite.
    bind = op.get_bind()
    for enum_name in ('customer_status', 'contact_kind', 'interaction_kind'):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
